server.port: 0

spring:
  application:
    name: user-service

  eureka:
    client:
      service-url:
        defalutZone: http://localhost:8761/eureka
      fetch-registry: true
      register-with-eureka: true